apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/ionnet: "true"
        io.kompose.service: web
    spec:
      containers:
        - image: dleeha/ion-app-web:latest #NOTE: to automate build
          name: web
          ports:
            - containerPort: 9090
          resources: {}
          volumeMounts:
            - mountPath: /etc/caddy/Caddyfile
              name: web-claim0
              subPath: Caddyfile
            - mountPath: /data
              name: caddy
      restartPolicy: Always
      volumes:
        - name: web-claim0
          configMap:
            name: web-caddy-file
        - name: caddy
          persistentVolumeClaim:
            claimName: web-claim0
status: {}
